spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials" #заменить на код

  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 40

  liquibase:
    change-log: db/changelog/db.changelog-master-dev.yaml

server:
  port: 9000
  forward-headers-strategy: framework

logging:
  status: enabled
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO

exception-handler:
  status: enabled
