spring:
  cloud:
    config:
      enabled: false
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 40

  liquibase:
    change-log: db/changelog/db.changelog-master-dev.yaml

server:
  port: 8082

exception-handler:
  status: enabled

logging:
  status: enabled

  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.oauth2: INFO
