confighost: http://localhost:8888

spring:
  application: news-service
  datasource:
    url: jdbc:postgresql://db_users:5432/news
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 50

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

server:
  port: 8082
  forward-headers-strategy: framework

exception-handler:
  status: enabled

logging:
  status: disabled
